language: node_js
node_js:
- '0.12'
cache:
  directories:
  - node_modules
addons:
  sauce_connect: true
env:
  global:
  - secure: IyXK9vLsOjreQuQOIIOgV2EpTOcWS6rwLmitv3A+4CwAw3VvbZyjOM0rRQ0yTvIg0MLoGukTlkh2xTjK9wTBdcqKNQ8Jjl9hnNnm3VXFAXSdnXhT9bjPZewcGVttYACWz/DaEDNfGDapT9gWLKcZ8G6hKUlJre3B3HolJh9vlUJsIJyn/wu5lfO3IVigVZNM0J2T0nvw7xDaIiAar1BM+PWrncsG4Roh4K+AnE9PjMWGazqxjmd5+RviJIhrMNEcnzpoS7tYQjNjYIh3NN7OFExhI8Cn1QNdIg6vyISbrQxJGIhl3iRxwmQ9Gkee953gkdlk7buyrRIInYiAe6FqabhBSnPlHV6ohGWCXT6KEhQuUCObpKNF2SOl5YlXZbHFDlFAyvd7qXAUSA1rok45ahJDd6VFdkdYXmnhO+ogzdSSmlKtXSpuUo5IELoDY5QOLD/0qSWVEMFRR8VQ2n/MlB+trijC5bTpg1JGnYBQzrXdz8BGhheTD95DrAJTtoP9QmEVKlYSsgKTrc/0xcfB+3FASiEtLYKvFDF3KhrGoJOJqupxt8YAxNOqeGj0wnXinJwQkMLJDB4smjweez3bWm85pNqBOC0IX2bBV81ZiftPJHVxU3gLIwS8kzfXXzu42rokY+f+lkFL2g8kPbjvMjfNeRM6O5nl3p6niUzuoUk=
  - secure: YBazbzFZltIpsJEF7blt/UmfYjEpuM8xxGbmpw7186gM48fMicO+84Km/hO9mgrMOUBQEPUde2V33PHP37f2OT8srLDRWx03TqrRWGeCTvlz+DNPTr9CBuYY0eaIGyGLUIPhT9IGZNmN1LR1jFt6a04Foor0OPOt8TpwkMrXJF8+PBa2Kqx8GB3SbL2sRQXwjMbpCZ3YqGqvrnBZO7feqxL9N1I5hP/ZaX9/igv0GY4R5hpLAu+lTZkyiDtjLtPPwjbcKbQaKqha7OOPl7lCUDjIwmD6qcnorJoTNdiccIjmNRwC7JwPcobV+oHhNPZ9w0G7Tniwqio86dBNVU/YLl58SKuHrzpWwwcmgmEmbE3kwfzPKF8F36sqrR1B8Q4nYfylwMJQn8L3dUt9H7ZudYPOBEhUCvpQjRoNJhpFxZtTW629HCdcxo9gsuYqwsLqdeq2JB0894f8Y9v/OMlHBj3sJgbYVla0jEFB0DcHsS20VnqG/4pB2IS8c8BykDD1XO4gnhxCiff9IIBtbG7vw0edJ3uyJSV9rupxsc837Qn46N/bX5DSNojam6ZlTFaekWADmd3NMBsZMjoAHvtJPHn6vU0VZNMf1Snzzedzg3o6NKOSPCmlmglGeKq7snECaN83J6IA08wS6JKMGqrdDqfPXz885IGW1SFIrgoIZAI=
